### ISSUE TITLE
Which Java For DerbyTimer with Raspbian?

### ISSUE THREAD

**Issue by TheFuzz4** [jeffpiazza/derbynet#148]
First off thank you for this amazing piece of software.  As our pack here in Westiminster CO is getting ready for our derby at the end of this month I've been tasked with migrating us over to DerbyNet.  

With the holidays I decided this was a perfect time to get all of our pi's installed and testing them as much as I can until we get the track out of storage here soon.  

With that being said I wanted to use a Pi4 8GB as our timer device

When attempting to launch the timer I'm getting

```
Error: LinkageError occurred while loading main class org.jeffpiazza.derby.TimerMain
	java.lang.UnsupportedClassVersionError: org/jeffpiazza/derby/TimerMain has been compiled by a more recent version of the Java Runtime (class file version 59.0), this version of the Java Runtime only recognizes class file versions up to 55.0
```

I have the java that came with raspbian

```
java --version
openjdk 11.0.9.1 2020-11-04
OpenJDK Runtime Environment (build 11.0.9.1+1-post-Raspbian-1deb10u2)
OpenJDK Server VM (build 11.0.9.1+1-post-Raspbian-1deb10u2, mixed mode)
```

I'm sure there is a simple solution for this just not the greatest with java.  I downloaded the openjdk15 and stuck it in my home dir and tried to run the derbynet.jar directly from that java but got errors about not able to find a class. 

Thanks for your help.

**Comment by jeffpiazza** [comment]
Sorry about this!  I noticed this myself just a few hours ago.

You didn't mention which build you're running, but 1188, also with 2020-01-01 date, should fix this.  Please let me know if you find it doesn't.

**Comment by TheFuzz4** [comment]
Hey @jeffpiazza thank you for the rapid response.  I just added the repos and installed today.  Just attempted an update from apt but no updates yet.  Is there a spot I can check the build?  Thanks.  If I need to pull it directly from this repo I can do that too was just following along with the docs :)

**Comment by jeffpiazza** [comment]
Hmm, not being able to run the jar at all, it's more challenging to determine the version number for the jar.

Maybe the expedient thing is to download the latest derby-timer.jar (1188 is now current) and see if it runs.

**Comment by TheFuzz4** [comment]
ok let me find that and I'll yank it down.  Assuming its in this repo

**Comment by TheFuzz4** [comment]
Ok confirmed that I am using 1188

```
dpkg -i derbynet-timer_v6.0-1188-20210101.deb 
(Reading database ... 98845 files and directories currently installed.)
Preparing to unpack derbynet-timer_v6.0-1188-20210101.deb ...
Unpacking derbynet-timer (6.0-1188) over (6.0-1188) ...
Setting up derbynet-timer (6.0-1188) ...
```

But still getting the same error tried as both pi and root with the same results.

**Comment by jeffpiazza** [comment]
Sorry, sorry, sorry -- 1188 had the build script changes, but the cached .class files contaminated the actual jar file.

Build 1190, just uploaded, should resolve this.

**Comment by TheFuzz4** [comment]
Mr. Hammond we're back in business (to quote the great Jurassic Park)  

Thanks @jeffpiazza I greatly appreciate your quick response that was awesome.
